// src/app/MainWindowView.vue
<script setup lang="ts" vapor>
import { ref } from "vue";
import AppHeader from "../components/AppHeader.vue";
import AppToolbar from "../components/AppToolbar.vue";
import type { ContextMenuItem, ImagePreviewItem } from "../components/componentTypes";
import ConfirmDialog from "../components/ConfirmDialog.vue";
import ContextMenu from "../components/ContextMenu.vue";
import ImagePreview from "../components/ImagePreview.vue";
import NoteEditor from "../components/NoteEditor.vue";
import NoteList from "../components/NoteList.vue";
import QMark from "../components/QMark.vue";
import SettingsDialog from "../components/SettingsDialog.vue";
import StatusBar from "../components/StatusBar.vue";
import Toast from "../components/Toast.vue";
import UpdateDownloadDialog from "../components/UpdateDownloadDialog.vue";
import type { MenuState } from "../features/menu/useMenuController";
import type { ToastState } from "../hooks/useToast";
import type { Translation } from "../i18n";
import type { UpdateDownloadProgress } from "../lib/updateProgress";
import type { UpdateInfo, UpdatePhase } from "../lib/updater";
import type { Note, NoteDraft } from "../types";

defineProps<{
  alwaysOnLabel: string;
  alwaysOnTop: boolean;
  appVersion: string;
  autoStart: boolean;
  checkingUpdate: boolean;
  contextItems: ContextMenuItem[];
  dockButtonLabel: string;
  editorNote: Note | null | undefined;
  hasUpdate: boolean;
  menu: MenuState | null;
  notes: Note[];
  ready: boolean;
  showDeleteAllConfirm: boolean;
  showSettings: boolean;
  t: Translation;
  toast: ToastState | null;
  updateDialogOpen: boolean;
  updateDownloadProgress: UpdateDownloadProgress | null;
  updateInfo: UpdateInfo | null;
  updatePhase: UpdatePhase;
}>();

const emit = defineEmits<{
  cancelEditor: [];
  checkUpdate: [];
  closeConfirmDeleteAll: [];
  closeMenu: [];
  closeSettings: [];
  closeWindow: [];
  collapseToDock: [];
  colorChange: [id: string, color: string];
  confirmDeleteAll: [];
  copyNote: [note: Note];
  deleteAll: [];
  deleteNote: [id: string];
  dragMainWindow: [event: PointerEvent];
  editNote: [note: Note];
  export: [];
  heightChange: [id: string, textHeight: number];
  import: [];
  minimizeWindow: [];
  newNote: [];
  openCurrentRelease: [];
  openMenu: [event: MouseEvent, noteId?: string];
  openSettings: [];
  reorderNotes: [draggedId: string, targetId: string, placement: "before" | "after"];
  saveDraft: [draft: NoteDraft];
  toggleAlwaysOnTop: [];
  toggleAutoStart: [];
  toggleLanguage: [];
  toggleNotePin: [id: string];
}>();

interface ImagePreviewState {
  index: number;
  items: ImagePreviewItem[];
}
const imagePreview = ref<ImagePreviewState | null>(null);

function previewImages(items: ImagePreviewItem[], index: number) {
  imagePreview.value = { index, items };
}
function forwardColorChange(id: string, color: string) {
  emit("colorChange", id, color);
}
function forwardContextMenu(event: MouseEvent, noteId: string) {
  emit("openMenu", event, noteId);
}
function forwardHeightChange(id: string, height: number) {
  emit("heightChange", id, height);
}
function forwardReorder(draggedId: string, targetId: string, placement: "before" | "after") {
  emit("reorderNotes", draggedId, targetId, placement);
}
</script>

<template>
  <main v-if="!ready" class="app-shell is-loading">
    <QMark class="loading-mark" />
  </main>
  <main v-else class="app-shell" @click="emit('closeMenu')" @contextmenu="emit('openMenu', $event)">
    <AppHeader
      :always-on-label="alwaysOnLabel"
      :always-on-top="alwaysOnTop"
      :t="t"
      @close="emit('closeWindow')"
      @drag-start="emit('dragMainWindow', $event)"
      @minimize="emit('minimizeWindow')"
      @toggle-always-on-top="emit('toggleAlwaysOnTop')"
    />
    <AppToolbar
      :has-update="hasUpdate"
      :notes-count="notes.length"
      :t="t"
      :update-version="updateInfo?.latestVersion"
      @delete-all="emit('deleteAll')"
      @new-note="emit('newNote')"
      @open-settings="emit('openSettings')"
      @toggle-language="emit('toggleLanguage')"
    />
    <NoteList
      :notes="notes"
      :t="t"
      @color-change="forwardColorChange"
      @context-menu="forwardContextMenu"
      @copy="emit('copyNote', $event)"
      @delete="emit('deleteNote', $event)"
      @edit="emit('editNote', $event)"
      @height-change="forwardHeightChange"
      @new-note="emit('newNote')"
      @preview-images="previewImages"
      @reorder="forwardReorder"
      @toggle-pin="emit('toggleNotePin', $event)"
    />

    <NoteEditor
      v-if="editorNote !== undefined"
      :note="editorNote"
      :t="t"
      @cancel="emit('cancelEditor')"
      @save="emit('saveDraft', $event)"
    />
    <SettingsDialog
      v-if="showSettings"
      :app-version="appVersion"
      :auto-start="autoStart"
      :checking-update="checkingUpdate"
      :has-update="hasUpdate"
      :t="t"
      @check-update="emit('checkUpdate')"
      @close="emit('closeSettings')"
      @export="emit('export')"
      @import="emit('import')"
      @open-current-release="emit('openCurrentRelease')"
      @toggle-auto-start="emit('toggleAutoStart')"
    />
    <UpdateDownloadDialog
      v-if="updateDialogOpen && updateInfo"
      :phase="updatePhase"
      :progress="updateDownloadProgress"
      :t="t"
      :update="updateInfo"
    />
    <ContextMenu
      v-if="menu"
      :items="contextItems"
      :x="menu.x"
      :y="menu.y"
      @close="emit('closeMenu')"
    />
    <ConfirmDialog
      v-if="showDeleteAllConfirm"
      :body="t.deleteAllBody"
      :cancel-label="t.cancel"
      :confirm-label="t.deleteAll"
      :title="t.confirmDeleteAll"
      @cancel="emit('closeConfirmDeleteAll')"
      @confirm="emit('confirmDeleteAll')"
    />
    <button
      :aria-label="dockButtonLabel"
      class="panel-dock-button"
      :title="dockButtonLabel"
      type="button"
      @click.stop="emit('collapseToDock')"
    >
      <QMark />
    </button>
    <StatusBar :notes-count="notes.length" :t="t" />
    <Toast :icon="toast?.icon" :kind="toast?.kind" :message="toast?.message ?? null" />
    <ImagePreview
      v-if="imagePreview"
      :initial-index="imagePreview.index"
      :items="imagePreview.items"
      :t="t"
      @close="imagePreview = null"
    />
  </main>
</template>

// src/app/MainWindowView.tsx
import { useState, type MouseEvent, type PointerEvent } from "react";
import { AppHeader } from "../components/AppHeader";
import { AppToolbar } from "../components/AppToolbar";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { ContextMenu, type ContextMenuItem } from "../components/ContextMenu";
import { ImagePreview, type ImagePreviewItem } from "../components/ImagePreview";
import { NoteEditor, type NoteDraft } from "../components/NoteEditor";
import { NoteList } from "../components/NoteList";
import { QMark } from "../components/QMark";
import { SettingsDialog } from "../components/SettingsDialog";
import { StatusBar } from "../components/StatusBar";
import { Toast } from "../components/Toast";
import { UpdateDownloadDialog } from "../components/UpdateDownloadDialog";
import type { MenuState } from "../features/menu/useMenuController";
import type { ToastState } from "../hooks/useToast";
import type { Translation } from "../i18n";
import type { UpdateDownloadProgress } from "../lib/updateProgress";
import type { UpdateInfo, UpdatePhase } from "../lib/updater";
import type { Note } from "../types";

interface MainWindowViewProps {
  alwaysOnLabel: string;
  alwaysOnTop: boolean;
  appVersion: string;
  autoStart: boolean;
  checkingUpdate: boolean;
  contextItems: ContextMenuItem[];
  dockButtonLabel: string;
  editorNote: Note | null | undefined;
  hasUpdate: boolean;
  menu: MenuState | null;
  notes: Note[];
  onCancelEditor: () => void;
  onCheckUpdate: () => void;
  onCloseConfirmDeleteAll: () => void;
  onCloseMenu: () => void;
  onCloseSettings: () => void;
  onCloseWindow: () => void;
  onCollapseToDock: () => void;
  onColorChange: (id: string, color: string) => void;
  onConfirmDeleteAll: () => void;
  onCopyNote: (note: Note) => void;
  onDeleteAll: () => void;
  onDeleteNote: (id: string) => void;
  onDragMainWindow: (event: PointerEvent<HTMLElement>) => void;
  onEditNote: (note: Note) => void;
  onExport: () => void;
  onHeightChange: (id: string, textHeight: number) => void;
  onImport: () => void;
  onMinimizeWindow: () => void;
  onNewNote: () => void;
  onOpenCurrentRelease: () => void;
  onOpenMenu: (event: MouseEvent<HTMLElement>, noteId?: string) => void;
  onOpenSettings: () => void;
  onReorderNotes: (draggedId: string, targetId: string, placement: "before" | "after") => void;
  onSaveDraft: (draft: NoteDraft) => void;
  onToggleAlwaysOnTop: () => void;
  onToggleAutoStart: () => void;
  onToggleLanguage: () => void;
  onToggleNotePin: (id: string) => void;
  ready: boolean;
  showDeleteAllConfirm: boolean;
  showSettings: boolean;
  t: Translation;
  toast: ToastState | null;
  updateDialogOpen: boolean;
  updateDownloadProgress: UpdateDownloadProgress | null;
  updateInfo: UpdateInfo | null;
  updatePhase: UpdatePhase;
}

interface ImagePreviewState {
  index: number;
  items: ImagePreviewItem[];
}

export function MainWindowView({
  alwaysOnLabel,
  alwaysOnTop,
  appVersion,
  autoStart,
  checkingUpdate,
  contextItems,
  dockButtonLabel,
  editorNote,
  hasUpdate,
  menu,
  notes,
  onCancelEditor,
  onCheckUpdate,
  onCloseConfirmDeleteAll,
  onCloseMenu,
  onCloseSettings,
  onCloseWindow,
  onCollapseToDock,
  onColorChange,
  onConfirmDeleteAll,
  onCopyNote,
  onDeleteAll,
  onDeleteNote,
  onDragMainWindow,
  onEditNote,
  onExport,
  onHeightChange,
  onImport,
  onMinimizeWindow,
  onNewNote,
  onOpenCurrentRelease,
  onOpenMenu,
  onOpenSettings,
  onReorderNotes,
  onSaveDraft,
  onToggleAlwaysOnTop,
  onToggleAutoStart,
  onToggleLanguage,
  onToggleNotePin,
  ready,
  showDeleteAllConfirm,
  showSettings,
  t,
  toast,
  updateDialogOpen,
  updateDownloadProgress,
  updateInfo,
  updatePhase,
}: MainWindowViewProps) {
  const [imagePreview, setImagePreview] = useState<ImagePreviewState | null>(null);

  if (!ready) {
    return (
      <main className="app-shell is-loading">
        <QMark className="loading-mark" />
      </main>
    );
  }

  return (
    <main className="app-shell" onClick={onCloseMenu} onContextMenu={onOpenMenu}>
      <AppHeader
        alwaysOnLabel={alwaysOnLabel}
        alwaysOnTop={alwaysOnTop}
        onClose={onCloseWindow}
        onDragStart={onDragMainWindow}
        onMinimize={onMinimizeWindow}
        onToggleAlwaysOnTop={onToggleAlwaysOnTop}
        t={t}
      />

      <AppToolbar
        hasUpdate={hasUpdate}
        notesCount={notes.length}
        onDeleteAll={onDeleteAll}
        onNewNote={onNewNote}
        onOpenSettings={onOpenSettings}
        onToggleLanguage={onToggleLanguage}
        t={t}
        updateVersion={updateInfo?.latestVersion}
      />

      <NoteList
        notes={notes}
        onColorChange={onColorChange}
        onContextMenu={onOpenMenu}
        onCopy={onCopyNote}
        onDelete={onDeleteNote}
        onEdit={onEditNote}
        onHeightChange={onHeightChange}
        onNewNote={onNewNote}
        onPreviewImages={(items, index) => setImagePreview({ index, items })}
        onReorder={onReorderNotes}
        onTogglePin={onToggleNotePin}
        t={t}
      />

      {editorNote !== undefined ? (
        <NoteEditor note={editorNote} onCancel={onCancelEditor} onSave={onSaveDraft} t={t} />
      ) : null}
      {showSettings ? (
        <SettingsDialog
          appVersion={appVersion}
          autoStart={autoStart}
          checkingUpdate={checkingUpdate}
          hasUpdate={hasUpdate}
          onCheckUpdate={onCheckUpdate}
          onClose={onCloseSettings}
          onExport={onExport}
          onImport={onImport}
          onOpenCurrentRelease={onOpenCurrentRelease}
          onToggleAutoStart={onToggleAutoStart}
          t={t}
        />
      ) : null}
      {updateDialogOpen && updateInfo ? (
        <UpdateDownloadDialog
          phase={updatePhase}
          progress={updateDownloadProgress}
          t={t}
          update={updateInfo}
        />
      ) : null}

      {menu ? (
        <ContextMenu items={contextItems} onClose={onCloseMenu} x={menu.x} y={menu.y} />
      ) : null}
      {showDeleteAllConfirm ? (
        <ConfirmDialog
          body={t.deleteAllBody}
          cancelLabel={t.cancel}
          confirmLabel={t.deleteAll}
          onCancel={onCloseConfirmDeleteAll}
          onConfirm={onConfirmDeleteAll}
          title={t.confirmDeleteAll}
        />
      ) : null}
      <button
        aria-label={dockButtonLabel}
        className="panel-dock-button"
        onClick={(event) => {
          event.stopPropagation();
          onCollapseToDock();
        }}
        title={dockButtonLabel}
        type="button"
      >
        <QMark />
      </button>
      <StatusBar notes={notes} t={t} />
      <Toast icon={toast?.icon} kind={toast?.kind} message={toast?.message ?? null} />
      {imagePreview ? (
        <ImagePreview
          initialIndex={imagePreview.index}
          items={imagePreview.items}
          onClose={() => setImagePreview(null)}
          t={t}
        />
      ) : null}
    </main>
  );
}
