// src/components/AppToolbar.vue
<script setup lang="ts" vapor>
import { computed } from "vue";
import { LanguagesIcon, PlusIcon, SettingsIcon, Trash2Icon } from "../icons";
import type { Translation } from "../i18n";
import Icon from "./Icon.vue";
import IconButton from "./IconButton.vue";

const props = defineProps<{
  hasUpdate: boolean;
  notesCount: number;
  t: Translation;
  updateVersion?: string;
}>();
const emit = defineEmits<{
  deleteAll: [];
  newNote: [];
  openSettings: [];
  toggleLanguage: [];
}>();

const settingsLabel = computed(() =>
  props.hasUpdate && props.updateVersion
    ? props.t.updateAvailableTitle(props.updateVersion)
    : props.t.settings,
);
</script>

<template>
  <div class="toolbar">
    <IconButton :label="t.newNote" @click="emit('newNote')">
      <template #icon><Icon :nodes="PlusIcon" :size="18" /></template>
    </IconButton>
    <IconButton
      class="is-danger"
      :disabled="notesCount === 0"
      :label="t.deleteAll"
      @click="emit('deleteAll')"
    >
      <template #icon><Icon :nodes="Trash2Icon" :size="18" /></template>
    </IconButton>
    <IconButton :badge="hasUpdate" :label="settingsLabel" @click="emit('openSettings')">
      <template #icon><Icon :nodes="SettingsIcon" :size="18" /></template>
    </IconButton>
    <IconButton :label="t.language" @click="emit('toggleLanguage')">
      <template #icon><Icon :nodes="LanguagesIcon" :size="18" /></template>
      {{ t.language }}
    </IconButton>
  </div>
</template>

// src/components/AppToolbar.tsx
import { Languages, Plus, Settings, Trash2 } from "lucide-react";
import type { Translation } from "../i18n";
import { IconButton } from "./IconButton";

interface AppToolbarProps {
  hasUpdate: boolean;
  notesCount: number;
  onDeleteAll: () => void;
  onNewNote: () => void;
  onOpenSettings: () => void;
  onToggleLanguage: () => void;
  t: Translation;
  updateVersion?: string;
}

export function AppToolbar({
  hasUpdate,
  notesCount,
  onDeleteAll,
  onNewNote,
  onOpenSettings,
  onToggleLanguage,
  t,
  updateVersion,
}: AppToolbarProps) {
  const settingsLabel =
    hasUpdate && updateVersion ? t.updateAvailableTitle(updateVersion) : t.settings;

  return (
    <div className="toolbar">
      <IconButton icon={<Plus size={18} />} label={t.newNote} onClick={onNewNote} />
      <IconButton
        className="is-danger"
        disabled={notesCount === 0}
        icon={<Trash2 size={18} />}
        label={t.deleteAll}
        onClick={onDeleteAll}
      />
      <IconButton
        badge={hasUpdate}
        icon={<Settings size={18} />}
        label={settingsLabel}
        onClick={onOpenSettings}
      />
      <IconButton icon={<Languages size={18} />} label={t.language} onClick={onToggleLanguage}>
        {t.language}
      </IconButton>
    </div>
  );
}
