// src/components/ConfirmDialog.vue
<script setup lang="ts" vapor>
defineProps<{
  body: string;
  cancelLabel: string;
  confirmLabel: string;
  title: string;
}>();

const emit = defineEmits<{
  cancel: [];
  confirm: [];
}>();
</script>

<template>
  <div class="modal-backdrop" @mousedown="emit('cancel')">
    <section aria-modal="true" class="confirm-dialog" role="alertdialog" @mousedown.stop>
      <h2>{{ title }}</h2>
      <p>{{ body }}</p>
      <footer>
        <button class="text-button" type="button" @click="emit('cancel')">
          {{ cancelLabel }}
        </button>
        <button class="danger-button" type="button" @click="emit('confirm')">
          {{ confirmLabel }}
        </button>
      </footer>
    </section>
  </div>
</template>

// src/components/ConfirmDialog.tsx
interface ConfirmDialogProps {
  body: string;
  cancelLabel: string;
  confirmLabel: string;
  onCancel: () => void;
  onConfirm: () => void;
  title: string;
}

export function ConfirmDialog({
  body,
  cancelLabel,
  confirmLabel,
  onCancel,
  onConfirm,
  title,
}: ConfirmDialogProps) {
  return (
    <div className="modal-backdrop" onMouseDown={onCancel}>
      <section
        aria-modal="true"
        className="confirm-dialog"
        onMouseDown={(event) => event.stopPropagation()}
        role="alertdialog"
      >
        <h2>{title}</h2>
        <p>{body}</p>
        <footer>
          <button className="text-button" onClick={onCancel} type="button">
            {cancelLabel}
          </button>
          <button className="danger-button" onClick={onConfirm} type="button">
            {confirmLabel}
          </button>
        </footer>
      </section>
    </div>
  );
}
