// src/components/ContextMenu.vue
<script setup lang="ts" vapor>
import { nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";
import { clampContextMenuPosition } from "./contextMenuPosition";
import type { ContextMenuItem } from "./componentTypes";
import Icon from "./Icon.vue";

const props = defineProps<{
  items: ContextMenuItem[];
  x: number;
  y: number;
}>();
const emit = defineEmits<{ close: [] }>();

const menuElement = ref<HTMLDivElement | null>(null);
const position = reactive({ left: props.x, top: props.y });

async function updatePosition() {
  await nextTick();
  const menu = menuElement.value;
  if (!menu) {
    return;
  }

  const bounds = menu.getBoundingClientRect();
  Object.assign(
    position,
    clampContextMenuPosition({
      menuHeight: bounds.height,
      menuWidth: bounds.width,
      viewportHeight: window.innerHeight,
      viewportWidth: window.innerWidth,
      x: props.x,
      y: props.y,
    }),
  );
}

function selectItem(item: ContextMenuItem) {
  item.onSelect();
  emit("close");
}

watch(() => [props.items.length, props.x, props.y], updatePosition, { flush: "post" });
onMounted(() => {
  void updatePosition();
  window.addEventListener("resize", updatePosition);
});
onBeforeUnmount(() => window.removeEventListener("resize", updatePosition));
</script>

<template>
  <div ref="menuElement" class="context-menu" :style="position" @click.stop @contextmenu.prevent>
    <button
      v-for="item in items"
      :key="item.id"
      :class="{ 'is-danger': item.destructive }"
      type="button"
      @click="selectItem(item)"
    >
      <Icon :nodes="item.icon" :size="16" />
      <span>{{ item.label }}</span>
    </button>
  </div>
</template>

// src/components/ContextMenu.tsx
import { useLayoutEffect, useRef, useState, type ReactNode } from "react";
import { clampContextMenuPosition } from "./contextMenuPosition";

export interface ContextMenuItem {
  destructive?: boolean;
  icon: ReactNode;
  id: string;
  label: string;
  onSelect: () => void;
}

interface ContextMenuProps {
  items: ContextMenuItem[];
  onClose: () => void;
  x: number;
  y: number;
}

export function ContextMenu({ items, onClose, x, y }: ContextMenuProps) {
  const menuRef = useRef<HTMLDivElement>(null);
  const [position, setPosition] = useState({ left: x, top: y });

  useLayoutEffect(() => {
    const updatePosition = () => {
      const menu = menuRef.current;
      if (!menu) return;

      const bounds = menu.getBoundingClientRect();
      const nextPosition = clampContextMenuPosition({
        menuHeight: bounds.height,
        menuWidth: bounds.width,
        viewportHeight: window.innerHeight,
        viewportWidth: window.innerWidth,
        x,
        y,
      });

      setPosition((current) =>
        current.left === nextPosition.left && current.top === nextPosition.top
          ? current
          : nextPosition,
      );
    };

    updatePosition();
    window.addEventListener("resize", updatePosition);
    return () => window.removeEventListener("resize", updatePosition);
  }, [items.length, x, y]);

  return (
    <div
      className="context-menu"
      onClick={(event) => event.stopPropagation()}
      onContextMenu={(event) => event.preventDefault()}
      ref={menuRef}
      style={position}
    >
      {items.map((item) => (
        <button
          className={item.destructive ? "is-danger" : ""}
          key={item.id}
          onClick={() => {
            item.onSelect();
            onClose();
          }}
          type="button"
        >
          {item.icon}
          <span>{item.label}</span>
        </button>
      ))}
    </div>
  );
}
