// src/components/EmptyState.tsx
import type { Translation } from "../i18n";
import { QMark } from "./QMark";

interface EmptyStateProps {
  onNewNote: () => void;
  t: Translation;
}

export function EmptyState({ onNewNote, t }: EmptyStateProps) {
  return (
    <section className="empty-state">
      <QMark className="empty-mark" />
      <h2>{t.emptyTitle}</h2>
      <p>{t.noNotesBody}</p>
      <button className="primary-button" onClick={onNewNote} type="button">
        {t.emptyAction}
      </button>
    </section>
  );
}

// src/components/EmptyState.vue
<script setup lang="ts" vapor>
import type { Translation } from "../i18n";
import QMark from "./QMark.vue";

defineProps<{ t: Translation }>();
const emit = defineEmits<{ newNote: [] }>();
</script>

<template>
  <section class="empty-state">
    <QMark class="empty-mark" />
    <h2>{{ t.emptyTitle }}</h2>
    <p>{{ t.noNotesBody }}</p>
    <button class="primary-button" type="button" @click="emit('newNote')">
      {{ t.emptyAction }}
    </button>
  </section>
</template>
