// src/components/Toast.vue
<script setup lang="ts" vapor>
import { ref, watch } from "vue";
import { CheckIcon, CircleAlertIcon, InfoIcon } from "../icons";
import type { ToastKind } from "../hooks/useToast";
import Icon from "./Icon.vue";

const props = withDefaults(
  defineProps<{
    icon?: boolean;
    kind?: ToastKind;
    message: string | null;
  }>(),
  { icon: true, kind: "success" },
);

const visibleIcon = ref(props.icon);
const visibleKind = ref(props.kind);
const visibleMessage = ref(props.message);

watch(
  () => [props.icon, props.kind, props.message] as const,
  ([icon, kind, message]) => {
    if (message) {
      visibleIcon.value = icon;
      visibleKind.value = kind;
      visibleMessage.value = message;
    }
  },
);

function clearHiddenMessage() {
  if (!props.message) {
    visibleMessage.value = null;
  }
}
</script>

<template>
  <div
    aria-live="polite"
    :class="['toast', `toast--${visibleKind}`, { 'is-visible': message }]"
    role="status"
    @transitionend="clearHiddenMessage"
  >
    <Icon
      v-if="visibleIcon && visibleKind === 'error'"
      aria-hidden="true"
      :nodes="CircleAlertIcon"
    />
    <Icon v-else-if="visibleIcon && visibleKind === 'info'" aria-hidden="true" :nodes="InfoIcon" />
    <Icon v-else-if="visibleIcon" aria-hidden="true" :nodes="CheckIcon" />
    <span>{{ visibleMessage }}</span>
  </div>
</template>

// src/components/Toast.tsx
import { Check, CircleAlert, Info } from "lucide-react";
import { useEffect, useState } from "react";
import type { ToastKind } from "../hooks/useToast";

interface ToastProps {
  icon?: boolean;
  kind?: ToastKind;
  message: string | null;
}

function getToastIcon(kind: ToastKind) {
  if (kind === "error") {
    return <CircleAlert aria-hidden="true" />;
  }

  if (kind === "info") {
    return <Info aria-hidden="true" />;
  }

  return <Check aria-hidden="true" />;
}

export function Toast({ icon = true, kind = "success", message }: ToastProps) {
  const [visibleIcon, setVisibleIcon] = useState(icon);
  const [visibleKind, setVisibleKind] = useState(kind);
  const [visibleMessage, setVisibleMessage] = useState(message);

  useEffect(() => {
    if (message) {
      setVisibleIcon(icon);
      setVisibleKind(kind);
      setVisibleMessage(message);
    }
  }, [icon, kind, message]);

  return (
    <div
      aria-live="polite"
      className={`toast toast--${visibleKind} ${message ? "is-visible" : ""}`}
      onTransitionEnd={() => {
        if (!message) {
          setVisibleMessage(null);
        }
      }}
      role="status"
    >
      {visibleIcon ? getToastIcon(visibleKind) : null}
      <span>{visibleMessage}</span>
    </div>
  );
}
