// src/App.tsx
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useCallback, useState } from "react";
import "./App.css";
import { DockWindowView } from "./app/DockWindowView";
import { MainWindowView } from "./app/MainWindowView";
import { useMenuController } from "./features/menu/useMenuController";
import { useNotesController, useNotesState } from "./features/notes/useNotesController";
import { useSettingsController, useSettingsState } from "./features/settings/useSettingsController";
import { useWindowController } from "./features/window/useWindowController";
import { useAppBoot } from "./hooks/useAppBoot";
import { useDockMode } from "./hooks/useDockMode";
import { useTauriEventBridge } from "./hooks/useTauriEventBridge";
import { useToast } from "./hooks/useToast";
import { useTrayMenuLabels } from "./hooks/useTrayMenuLabels";
import { useUpdateManager } from "./hooks/useUpdateManager";
import { useWindowStatePersistence } from "./hooks/useWindowStatePersistence";
import { translations } from "./i18n";
import { isTauriRuntime } from "./lib/env";
import { prepareEditorForUpdate } from "./lib/updatePreparation";
import { DOCK_WINDOW_LABEL, MAIN_WINDOW_LABEL, captureWindowState } from "./lib/windowControls";
import type { Note } from "./types";

function App() {
  const [editorNote, setEditorNote] = useState<Note | null | undefined>(undefined);
  const [ready, setReady] = useState(false);
  const [showDeleteAllConfirm, setShowDeleteAllConfirm] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const { showToast, toast } = useToast();
  const { commitNotes, notes, notesRef, setNotes } = useNotesState();
  const { setSettings, settings, settingsRef } = useSettingsState();

  const currentWindowLabel = isTauriRuntime() ? getCurrentWindow().label : MAIN_WINDOW_LABEL;
  const isDockWindow = currentWindowLabel === DOCK_WINDOW_LABEL;
  const t = translations[settings.language];
  const dockToggleLabel = settings.docked ? t.switchMainWindow : t.switchFloatingBall;
  const alwaysOnLabel = settings.alwaysOnTop ? t.alwaysOff : t.alwaysOn;
  const editorOpen = editorNote !== undefined;

  const {
    handleExport,
    handleImport,
    persistSettings,
    toggleAlwaysOnTop,
    toggleAutoStart,
    toggleLanguage,
  } = useSettingsController({
    commitNotes,
    notesRef,
    setSettings,
    settingsRef,
    showToast,
    t,
  });

  const prepareForUpdate = useCallback(async () => {
    if (!settingsRef.current.docked) {
      const snapshot = await captureWindowState(MAIN_WINDOW_LABEL);
      await persistSettings(snapshot ? { window: snapshot } : {});
    } else {
      await persistSettings({});
    }

    await prepareEditorForUpdate();
  }, [persistSettings, settingsRef]);

  const {
    appVersion,
    checkingUpdate,
    handleCheckUpdate,
    handleOpenCurrentRelease,
    updateDialogOpen,
    updateDownloadProgress,
    updateInfo,
    updatePhase,
  } = useUpdateManager({
    currentWindowLabel,
    language: settings.language,
    prepareForUpdate,
    ready,
    showToast,
  });

  const {
    collapseToQIcon,
    concealDockIcon,
    dockDragRef,
    dockGuardRef,
    dragQIcon,
    finishQIconDrag,
    moveQIcon,
    openMainFromDockIcon,
    persistIconSnap,
    restoreDock,
    revealDockIcon,
    toggleDockOnEdge,
  } = useDockMode({
    currentWindowLabel,
    persistSettings,
    settingsRef,
  });

  const {
    closeEditor,
    handleCopy,
    handleDelete,
    handleDeleteAll,
    handleSaveDraft,
    openEditor,
    patchNote,
    reorderNotes,
  } = useNotesController({
    commitNotes,
    editorNote,
    notesRef,
    restoreDock,
    setEditorNote,
    settingsRef,
    showToast,
    t,
  });

  const { closeWindow, dragMainWindow, minimizeWindow, quitApp } = useWindowController({
    collapseToQIcon,
  });

  const { closeMenu, getContextItems, getDockMenuItems, menu, openDockMenu, openMenu } =
    useMenuController({
      alwaysOnLabel,
      dockToggleLabel,
      handleCopy,
      handleDelete,
      notesCount: notes.length,
      notesRef,
      onDeleteAll: () => setShowDeleteAllConfirm(true),
      openEditor,
      patchNote,
      quitApp,
      settings,
      t,
      toggleAlwaysOnTop,
      toggleDockOnEdge,
      toggleLanguage,
    });

  useAppBoot({
    currentWindowLabel,
    notesRef,
    settingsRef,
    setNotes,
    setReady,
    setSettings,
  });

  useTrayMenuLabels({
    alwaysOnLabel,
    dockToggleLabel,
    ready,
    t,
  });

  useTauriEventBridge({
    commitNotes,
    notesRef,
    ready,
    restoreDock,
    setSettings,
    settingsRef,
    showToast,
    toggleAlwaysOnTop,
    toggleDockOnEdge,
    toggleLanguage,
  });

  useWindowStatePersistence({
    currentWindowLabel,
    dockDragRef,
    dockGuardRef,
    editorOpen,
    persistIconSnap,
    persistSettings,
    ready,
    settingsRef,
  });

  if (isDockWindow) {
    return (
      <DockWindowView
        menu={menu}
        menuItems={getDockMenuItems()}
        onCloseMenu={closeMenu}
        onConcealDockIcon={() => void concealDockIcon()}
        onDockDragEnd={() => void finishQIconDrag()}
        onDockDragMove={() => void moveQIcon()}
        onDockDragStart={() => void dragQIcon()}
        onOpenDockMenu={(event) => void openDockMenu(event)}
        onOpenMain={() => void openMainFromDockIcon()}
        onRevealDockIcon={() => void revealDockIcon()}
        ready={ready}
        t={t}
        toast={toast}
      />
    );
  }

  return (
    <MainWindowView
      alwaysOnLabel={alwaysOnLabel}
      alwaysOnTop={settings.alwaysOnTop}
      appVersion={appVersion}
      autoStart={settings.autoStart}
      checkingUpdate={checkingUpdate}
      contextItems={getContextItems()}
      dockButtonLabel={t.switchFloatingBall}
      editorNote={editorNote}
      hasUpdate={Boolean(updateInfo)}
      menu={menu}
      notes={notes}
      onCancelEditor={() => void closeEditor()}
      onCheckUpdate={() => void handleCheckUpdate()}
      onCloseConfirmDeleteAll={() => setShowDeleteAllConfirm(false)}
      onCloseMenu={closeMenu}
      onCloseSettings={() => setShowSettings(false)}
      onCloseWindow={() => void closeWindow()}
      onCollapseToDock={() => void collapseToQIcon({ useRevealAnchor: true })}
      onColorChange={(id, color) => void patchNote(id, { color })}
      onConfirmDeleteAll={() => {
        setShowDeleteAllConfirm(false);
        void handleDeleteAll();
      }}
      onCopyNote={(note) => void handleCopy(note)}
      onDeleteAll={() => setShowDeleteAllConfirm(true)}
      onDeleteNote={(id) => void handleDelete(id)}
      onDragMainWindow={dragMainWindow}
      onEditNote={(note) => void openEditor(note)}
      onExport={() => void handleExport()}
      onHeightChange={(id, textHeight) => void patchNote(id, { textHeight })}
      onImport={() => void handleImport()}
      onMinimizeWindow={() => void minimizeWindow()}
      onNewNote={() => void openEditor(null)}
      onOpenCurrentRelease={() => void handleOpenCurrentRelease()}
      onOpenMenu={openMenu}
      onOpenSettings={() => setShowSettings(true)}
      onReorderNotes={(draggedId, targetId, placement) =>
        void reorderNotes(draggedId, targetId, placement)
      }
      onSaveDraft={(draft) => void handleSaveDraft(draft)}
      onToggleAlwaysOnTop={() => void toggleAlwaysOnTop()}
      onToggleAutoStart={() => void toggleAutoStart()}
      onToggleLanguage={() => void toggleLanguage()}
      onToggleNotePin={(id) => {
        const note = notesRef.current.find((item) => item.id === id);
        if (note) {
          void patchNote(id, { pinned: !note.pinned });
        }
      }}
      ready={ready}
      showDeleteAllConfirm={showDeleteAllConfirm}
      showSettings={showSettings}
      t={t}
      toast={toast}
      updateDialogOpen={updateDialogOpen}
      updateDownloadProgress={updateDownloadProgress}
      updateInfo={updateInfo}
      updatePhase={updatePhase}
    />
  );
}

export default App;

// src/App.vue
<script setup lang="ts" vapor>
import { getCurrentWindow } from "@tauri-apps/api/window";
import { computed, ref } from "vue";
import "./App.css";
import DockWindowView from "./app/DockWindowView.vue";
import MainWindowView from "./app/MainWindowView.vue";
import { useMenuController } from "./features/menu/useMenuController";
import { useNotesController, useNotesState } from "./features/notes/useNotesController";
import { useSettingsController, useSettingsState } from "./features/settings/useSettingsController";
import { useWindowController } from "./features/window/useWindowController";
import { useAppBoot } from "./hooks/useAppBoot";
import { useDockMode } from "./hooks/useDockMode";
import { useTauriEventBridge } from "./hooks/useTauriEventBridge";
import { useToast } from "./hooks/useToast";
import { useTrayMenuLabels } from "./hooks/useTrayMenuLabels";
import { useUpdateManager } from "./hooks/useUpdateManager";
import { useWindowStatePersistence } from "./hooks/useWindowStatePersistence";
import { translations } from "./i18n";
import { isTauriRuntime } from "./lib/env";
import { prepareEditorForUpdate } from "./lib/updatePreparation";
import { DOCK_WINDOW_LABEL, MAIN_WINDOW_LABEL, captureWindowState } from "./lib/windowControls";
import type { Note, NoteDraft } from "./types";

const editorNote = ref<Note | null | undefined>(undefined);
const ready = ref(false);
const showDeleteAllConfirm = ref(false);
const showSettings = ref(false);
const { showToast, toast } = useToast();
const { commitNotes, notes } = useNotesState();
const { settings } = useSettingsState();

const currentWindowLabel = isTauriRuntime() ? getCurrentWindow().label : MAIN_WINDOW_LABEL;
const isDockWindow = currentWindowLabel === DOCK_WINDOW_LABEL;
const t = computed(() => translations[settings.value.language]);
const dockToggleLabel = computed(() =>
  settings.value.docked ? t.value.switchMainWindow : t.value.switchFloatingBall,
);
const alwaysOnLabel = computed(() =>
  settings.value.alwaysOnTop ? t.value.alwaysOff : t.value.alwaysOn,
);
const editorOpen = computed(() => editorNote.value !== undefined);
const language = computed(() => settings.value.language);

const {
  handleExport,
  handleImport,
  persistSettings,
  toggleAlwaysOnTop,
  toggleAutoStart,
  toggleLanguage,
} = useSettingsController({ commitNotes, notes, settings, showToast, t });

async function prepareForUpdate() {
  if (!settings.value.docked) {
    const snapshot = await captureWindowState(MAIN_WINDOW_LABEL);
    await persistSettings(snapshot ? { window: snapshot } : {});
  } else {
    await persistSettings({});
  }
  await prepareEditorForUpdate();
}

const {
  appVersion,
  checkingUpdate,
  handleCheckUpdate,
  handleOpenCurrentRelease,
  hasUpdate,
  updateDialogOpen,
  updateDownloadProgress,
  updateInfo,
  updatePhase,
} = useUpdateManager({
  currentWindowLabel,
  language,
  prepareForUpdate,
  ready,
  showToast,
});

const {
  collapseToQIcon,
  concealDockIcon,
  dockDrag,
  dockGuard,
  dragQIcon,
  finishQIconDrag,
  moveQIcon,
  openMainFromDockIcon,
  persistIconSnap,
  restoreDock,
  revealDockIcon,
  toggleDockOnEdge,
} = useDockMode({ currentWindowLabel, persistSettings, settings });

const {
  closeEditor,
  handleCopy,
  handleDelete,
  handleDeleteAll,
  handleSaveDraft,
  openEditor,
  patchNote,
  reorderNotes,
} = useNotesController({
  commitNotes,
  editorNote,
  notes,
  restoreDock,
  settings,
  showToast,
  t,
});

const { closeWindow, dragMainWindow, minimizeWindow, quitApp } = useWindowController(() =>
  collapseToQIcon(),
);

const { closeMenu, contextItems, dockMenuItems, menu, openDockMenu, openMenu } = useMenuController({
  alwaysOnLabel,
  dockToggleLabel,
  handleCopy,
  handleDelete,
  notes,
  onDeleteAll: () => {
    showDeleteAllConfirm.value = true;
  },
  openEditor,
  patchNote,
  quitApp,
  settings,
  t,
  toggleAlwaysOnTop,
  toggleDockOnEdge,
  toggleLanguage,
});

useAppBoot({ currentWindowLabel, notes, ready, settings });
useTrayMenuLabels({ alwaysOnLabel, dockToggleLabel, ready, t });
useTauriEventBridge({
  commitNotes,
  notes,
  ready,
  restoreDock,
  settings,
  showToast,
  toggleAlwaysOnTop,
  toggleDockOnEdge,
  toggleLanguage,
});
useWindowStatePersistence({
  currentWindowLabel,
  dockDrag,
  dockGuard,
  editorOpen,
  persistIconSnap,
  persistSettings,
  ready,
  settings,
});

function confirmDeleteAll() {
  showDeleteAllConfirm.value = false;
  void handleDeleteAll();
}

function changeNoteColor(id: string, color: string) {
  void patchNote(id, { color });
}

function changeNoteHeight(id: string, textHeight: number) {
  void patchNote(id, { textHeight });
}

function reorderNote(draggedId: string, targetId: string, placement: "before" | "after") {
  void reorderNotes(draggedId, targetId, placement);
}

function saveDraft(draft: NoteDraft) {
  void handleSaveDraft(draft);
}

function toggleNotePin(id: string) {
  const note = notes.value.find((item) => item.id === id);
  if (note) {
    void patchNote(id, { pinned: !note.pinned });
  }
}
</script>

<template>
  <DockWindowView
    v-if="isDockWindow"
    :menu="menu"
    :menu-items="dockMenuItems"
    :ready="ready"
    :t="t"
    :toast="toast"
    @close-menu="closeMenu"
    @conceal-dock-icon="concealDockIcon"
    @dock-drag-end="finishQIconDrag"
    @dock-drag-move="moveQIcon"
    @dock-drag-start="dragQIcon"
    @open-dock-menu="openDockMenu"
    @open-main="openMainFromDockIcon"
    @reveal-dock-icon="revealDockIcon"
  />
  <MainWindowView
    v-else
    :always-on-label="alwaysOnLabel"
    :always-on-top="settings.alwaysOnTop"
    :app-version="appVersion"
    :auto-start="settings.autoStart"
    :checking-update="checkingUpdate"
    :context-items="contextItems"
    :dock-button-label="t.switchFloatingBall"
    :editor-note="editorNote"
    :has-update="hasUpdate"
    :menu="menu"
    :notes="notes"
    :ready="ready"
    :show-delete-all-confirm="showDeleteAllConfirm"
    :show-settings="showSettings"
    :t="t"
    :toast="toast"
    :update-dialog-open="updateDialogOpen"
    :update-download-progress="updateDownloadProgress"
    :update-info="updateInfo"
    :update-phase="updatePhase"
    @cancel-editor="closeEditor"
    @check-update="handleCheckUpdate"
    @close-confirm-delete-all="showDeleteAllConfirm = false"
    @close-menu="closeMenu"
    @close-settings="showSettings = false"
    @close-window="closeWindow"
    @collapse-to-dock="collapseToQIcon({ useRevealAnchor: true })"
    @color-change="changeNoteColor"
    @confirm-delete-all="confirmDeleteAll"
    @copy-note="handleCopy"
    @delete-all="showDeleteAllConfirm = true"
    @delete-note="handleDelete"
    @drag-main-window="dragMainWindow"
    @edit-note="openEditor"
    @export="handleExport"
    @height-change="changeNoteHeight"
    @import="handleImport"
    @minimize-window="minimizeWindow"
    @new-note="openEditor(null)"
    @open-current-release="handleOpenCurrentRelease"
    @open-menu="openMenu"
    @open-settings="showSettings = true"
    @reorder-notes="reorderNote"
    @save-draft="saveDraft"
    @toggle-always-on-top="toggleAlwaysOnTop"
    @toggle-auto-start="toggleAutoStart"
    @toggle-language="toggleLanguage"
    @toggle-note-pin="toggleNotePin"
  />
</template>
